# coding: utf-8
#
# Generated by sqlacodegen
#
from sqlalchemy import Column, DECIMAL, Date, Enum, Float, ForeignKey, SmallInteger, String, TIMESTAMP, Table, Time, text
from sqlalchemy.dialects.mysql import INTEGER, SMALLINT, TINYINT
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class RVenueitem(Base):
    __tablename__ = 'r_venueitem'

    r_VenueId = Column(INTEGER, primary_key=True, server_default=text("'0'"))
    r_VenueInstance = Column(INTEGER, nullable=False, server_default=text("'0'"))
    r_VenueName = Column(String(128))
    r_VenueEventType = Column(Enum('TRIATHLON', 'DUATHLON', 'SPLASHNDASH', 'AQUABIKE'), nullable=False, server_default=text("'TRIATHLON'"))
    r_VenueType = Column(Enum('OTHER', 'MTNBIKE', 'SPRINT', 'OLYMPIC', 'INTL', 'HALF', 'IM'))
    r_VenueSwim = Column(Float)
    r_VenueSwimunits = Column(Enum('KMS', 'YARDS', 'MILES'))
    r_VenueBike = Column(Float)
    r_VenueBikeunits = Column(Enum('KMS', 'YARDS', 'MILES'))
    r_VenueRun = Column(Float)
    r_VenueRununits = Column(Enum('KMS', 'YARDS', 'MILES'))
    r_VenueWebsite = Column(String(128))
    r_VenueMgmt = Column(String(128))
    r_VenueDesc = Column(String(128))
    r_VenueCity = Column(String(64))
    r_VenueState = Column(String(8))
    r_VenueLocId = Column(INTEGER, nullable=False, server_default=text("'0'"))
    r_VenueCurrent = Column(TINYINT(1))


class RVenuelocateitem(Base):
    __tablename__ = 'r_venuelocateitem'
    __table_args__ = {'comment': 'Lat/Long for each unique venue location'}

    r_LocationId = Column(INTEGER, primary_key=True)
    r_VenueCount = Column(INTEGER, server_default=text("'0'"))
    r_VenueLat = Column(Float(9), nullable=False, server_default=text("'0.000000'"))
    r_VenueLong = Column(Float(9), nullable=False, server_default=text("'0.000000'"))


class RRaceitem(Base):
    __tablename__ = 'r_raceitem'

    r_RaceId = Column(INTEGER(10), primary_key=True, server_default=text("'0000000000'"))
    r_UpdateDate = Column(TIMESTAMP, nullable=False, server_default=text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"))
    r_RaceVenueId = Column(ForeignKey('r_venueitem.r_VenueId'), index=True)
    r_RaceDate = Column(Date)
    r_TransData = Column(TINYINT(1))
    r_SplitData = Column(TINYINT(1))
    r_AgeData = Column(TINYINT)
    r_IMQual = Column(TINYINT(1))
    r_703Qual = Column(TINYINT(1))
    r_OrigResults = Column(String(128))
    r_RaceNote = Column(String(128))

    r_venueitem = relationship('RVenueitem')


t_r_resultitem = Table(
    'r_resultitem', metadata,
    Column('r_Id', INTEGER, nullable=False, unique=True),
    Column('r_RaceId', ForeignKey('r_raceitem.r_RaceId'), nullable=False, index=True, server_default=text("'0000000000'")),
    Column('r_BibNumber', SMALLINT),
    Column('r_OverallPlace', SMALLINT),
    Column('r_DivisionPlace', SMALLINT),
    Column('r_GenderPlace', SMALLINT),
    Column('r_TotalTime', Time),
    Column('r_LastName', String(32)),
    Column('r_FirstName', String(32)),
    Column('r_Gender', Enum('NONE', 'M', 'F'), index=True),
    Column('r_Age', SMALLINT),
    Column('r_City', String(32)),
    Column('r_State', String(4)),
    Column('r_Country', String(32)),
    Column('r_Division', Enum('NONE', 'MPRO', 'WPRO', 'MELITE', 'WELITE', 'CLYDE', 'ATHENA', 'RELAYO', 'RELAYM', 'RELAYF', 'M1-19', 'M18-24', 'M20-24', 'M25-29', 'M30-34', 'M35-39', 'M40-44', 'M45-49', 'M50-54', 'M55-59', 'M60-64', 'M65-69', 'M70-74', 'M75-79', 'M80-84', 'M85-89', 'M90-94', 'W1-19', 'W18-24', 'W20-24', 'W25-29', 'W30-34', 'W35-39', 'W40-44', 'W45-49', 'W50-54', 'W55-59', 'W60-64', 'W65-69', 'W70-74', 'W75-79', 'W80-84', 'W85-89', 'W90-94'), index=True),
    Column('r_SwimDiv', SMALLINT),
    Column('r_SwimGender', SMALLINT),
    Column('r_SwimOverall', SMALLINT),
    Column('r_SwimTime', Time),
    Column('r_SwimPace', Time),
    Column('r_T1Div', SMALLINT),
    Column('r_T1Gender', SMALLINT),
    Column('r_T1Overall', SMALLINT),
    Column('r_T1Time', Time),
    Column('r_BikeDiv', SMALLINT),
    Column('r_BikeGender', SMALLINT),
    Column('r_BikeOverall', SMALLINT),
    Column('r_BikeTime', Time),
    Column('r_BikePace', DECIMAL(3, 1)),
    Column('r_T2Div', SMALLINT),
    Column('r_T2Gender', SMALLINT),
    Column('r_T2Overall', SMALLINT),
    Column('r_T2Time', Time),
    Column('r_RunDiv', SMALLINT),
    Column('r_RunGender', SMALLINT),
    Column('r_RunOverall', SMALLINT),
    Column('r_RunTime', Time),
    Column('r_RunPace', Time),
    Column('r_NoTransDiv', SmallInteger),
    Column('r_NoTransGender', SmallInteger),
    Column('r_NoTransOverall', SmallInteger),
    Column('r_Penalty', Time),
    Column('r_HawaiiQual', TINYINT(1)),
    Column('r_HalfQual', TINYINT(1))
)

